# Variable Values
# Generated by Intelligent Terraform Agent

project_name = "my-web-app"
aws_region = "us-east-1"
vpc_cidr = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
availability_zone = "us-east-1a"
ami_id = "ami-0c02fb55956c7d316"
instance_type = "t3.micro"
key_name = "my-key"
db_instance_class = "db.t3.micro"
db_name = "myapp"
db_username = "admin"
db_password = "changeme123"
