name: Track GitHub Traffic

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  log-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch traffic data
        uses: jakejarvis/github-traffic-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: traffic-log.csv

      - name: Commit traffic log
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add traffic-log.csv
          git commit -m "Update traffic log"
          git push

