repos:
-   repo: local
    hooks:
    -   id: validate-context
        name: Validate project context
        entry: python scripts/validate_context.py
        language: python
        types: [python, yaml, markdown, terraform, hcl, json]
        stages: [commit, push]
        always_run: true
        verbose: true
        pass_filenames: false

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        entry: isort --profile black
        types: [python]
