#!/bin/bash
# Deployment script for Formatted Test
# Generated by Intelligent Infrastructure Agent

set -e

echo "🚀 Deploying Formatted Test..."

# Check if terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform is not installed. Please install Terraform first."
    exit 1
fi

# Check if AWS CLI is configured
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS CLI is not configured. Please run 'aws configure' first."
    exit 1
fi

# Navigate to terraform directory
cd terraform

# Initialize Terraform
echo "📦 Initializing Terraform..."
terraform init

# Plan the deployment
echo "📋 Planning deployment..."
terraform plan

# Ask for confirmation
read -p "Do you want to apply this configuration? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🏗️ Applying configuration..."
    terraform apply -auto-approve
    echo "✅ Deployment completed!"
    
    # Show outputs
    echo "📊 Infrastructure outputs:"
    terraform output
else
    echo "❌ Deployment cancelled."
fi
