#!/bin/bash
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd

# Create a simple test page
cat > /var/www/html/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>AI-AH Lab Test</title>
</head>
<body>
    <h1>AI-AH Agent Test Environment</h1>
    <p>This is a test deployment generated by the AI-AH agent.</p>
    <p>Environment: LAB</p>
    <p>Timestamp: $(date)</p>
</body>
</html>
EOF

systemctl restart httpd
