# Variable Values
# Generated by Intelligent Terraform Agent

project_name = "test"
aws_region = "us-east-1"
environment = "dev"
vpc_cidr = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
availability_zone = "us-east-1a"
ami_id = "ami-0c02fb55956c7d316"
instance_type = "t3.micro"
key_name = "test-dev-key"
db_instance_class = "db.t3.micro"
db_name = "test-db"
db_username = "admin"
db_password = "Adminadmin@1234"
high_availability = false
monitoring = true
backup = true